kind: pipeline
type: docker
name: default

steps:
  - name: build-and-restart
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy-host:2375
    commands:
      - docker-compose up -d tripbot_website