kind: pipeline
type: docker
name: default

steps:
  - name: build-and-restart
    image: docker
    network_mode: bridge
    privileged: true
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    commands:
      - tail -f /dev/null
      # - docker compose up tripbot_website -d --force-recreate --build --remove-orphans