kind: pipeline
type: docker
name: default

steps:
  - name: build-and-restart
    image: docker
    network_mode: bridge
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    commands:
      - docker-compose up -d tripbot_website