kind: pipeline
type: docker
name: default

steps:
  - name: build-and-restart
    image: docker
    privileged: true
    commands:
      # - docker compose -f docker-compose.host.yml --project-name tripsit-live up tripbot_website -d --force-recreate --build
      - tail -f /dev/null
    # volumes:
    # - name: dockersock
    #   path: /var/run/docker.sock
    environment:
      NODE_ENV:
        from_secret: NODE_ENV
      XID:
        from_secret: XID
      PUID:
        from_secret: PUID
      PGID:
        from_secret: PGID
      TIME_ZONE:
        from_secret: TIME_ZONE
      TZ:
        from_secret: TZ
      USERDIR:
        from_secret: USERDIR
      DOCKERDIR:
        from_secret: DOCKERDIR
      SECRETSDIR:
        from_secret: SECRETSDIR
      LOCAL_MOUNT:
        from_secret: LOCAL_MOUNT
      DNS_DOMAIN:
        from_secret: DNS_DOMAIN
      OTHER_DOMAIN:
        from_secret: OTHER_DOMAIN
      DOCKER_HOST:
        from_secret: DOCKER_HOST
      
volumes:
- name: dockersock
  host:
#     path: /var/run/docker.sock
# - name: dockercompose
#   host:
#     path: /home/moonbear/tripsit-prod/docker-compose.yml

