kind: pipeline
type: docker
name: default

steps:
  - name: Rebuild Website
    image: docker
    privileged: true
    commands:
      - apk update
      - apk upgrade
      - apk add --no-cache git
      - docker compose -f docker-compose.host.yml --project-name tripsit-live up tripbot_website -d --force-recreate --build
    environment:
      NODE_ENV:
        from_secret: NODE_ENV
      XID:
        from_secret: XID
      PUID:
        from_secret: PUID
      PGID:
        from_secret: PGID
      TIME_ZONE:
        from_secret: TIME_ZONE
      TZ:
        from_secret: TZ
      USERDIR:
        from_secret: USERDIR
      DOCKERDIR:
        from_secret: DOCKERDIR
      SECRETSDIR:
        from_secret: SECRETSDIR
      LOCAL_MOUNT:
        from_secret: LOCAL_MOUNT
      DNS_DOMAIN:
        from_secret: DNS_DOMAIN
      OTHER_DOMAIN:
        from_secret: OTHER_DOMAIN
      DOCKER_HOST:
        from_secret: DOCKER_HOST
      DOCKER_BUILDKIT:
        from_secret: DOCKER_BUILDKIT

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 1123644407434973255
      webhook_token: 73CXRJKNIwOUHyiVWQiJ4lxUllY2__BMH_lIrB6_XdTDH7dAPk0b_MZ3-TQAXiAj7cH6
      avatar_url: https://i.imgur.com/tnw3I34.png
      username: 'Drone CI'
      message: |
        {{#success build.status}}
        Build {{build.number}} succeeded.
        {{else}}
        Build {{build.number}} failed.
        {{/success}}
        Build time: {{build.started}}
        Commit message: {{commit.message}}
        Commit author: {{commit.author}}
        Commit branch: {{commit.branch}}
        {{#success build.status}}
        View logs: <{{build.link}}>
        {{else}}
        View failed job: <{{build.link}}>
        {{/success}}

trigger:
  branch:
  - main
trigger:
  event:
  - push