kind: pipeline
type: docker
name: default

steps:
  - name: build-and-restart
    image: docker
    privileged: true
    commands:
      # - docker compose -f docker-compose.host.yml --project-name tripsit-live up tripbot_website -d --force-recreate --build
      - tail -f /dev/null
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    - name: dockercompose
      path: /drone/src/docker/
      
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: dockercompose
  host:
    path: /docker/

