kind: pipeline
# type: docker
name: default

steps:
  - name: build-and-restart
    image: docker:dind
    network_mode: socket-net
    privileged: true
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
    commands:
      - docker ps -a
      # - docker compose up tripbot_website --force-recreate --build --remove-orphans
      - tail -f /dev/null