kind: pipeline
type: docker
name: Deploy Website

steps:
  - name: Docker Compose
    image: docker
    privileged: true
    commands:
      - apk update
      - apk upgrade
      - apk add --no-cache git
      - docker compose -f docker-compose.host.yml --project-name tripbot up tripbot_website -d --force-recreate --build
      # - tail -f /dev/null
    environment:
      DOCKER_HOST:
        from_secret: DOCKER_HOST
      DOCKER_BUILDKIT:
        from_secret: DOCKER_BUILDKIT

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: WEBHOOK_ID
      webhook_token:
        from_secret: WEBHOOK_TOKEN
      avatar_url: https://i.imgur.com/tnw3I34.png
      username: 'Drone CI'
      message: |
        {{#success build.status}}
        Build {{build.number}} succeeded.
        {{else}}
        Build {{build.number}} failed.
        {{/success}}
        Build time: {{build.started}}
        Commit message: {{commit.message}}
        Commit author: {{commit.author}}
        Commit branch: {{commit.branch}}
        {{#success build.status}}
        View logs: <{{build.link}}>
        {{else}}
        View failed job: <{{build.link}}>
        {{/success}}

trigger:
  branch:
  - main
trigger:
  event:
  # - cron
  - custom
  - push
  # - pull_request
  # - tag
  # - promote
  # - rollback