version: '3.9'
services:
  tripbot_website:
    container_name: tripbot_website
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    networks:
        - tripbot-net
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env

networks: 
  tripbot-net:
    driver: bridge
    name: tripbot-net
