version: '3.9'

name: tripsit-dev

########################### EXTENSION FIELDS
# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID
 
# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

services:
  tripbot_website:
    <<: *common-keys-apps
    build:
      context: ./
      dockerfile: ./Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    container_name: tripbot_website
    profiles: ["apps", "frontend", "tripbot", "all"]
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    networks:
      - tripbot-net
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    volumes:
      - ./src:/usr/src/app/src # Needed for hot-reloading of source code
      - ./cypress:/usr/src/app/cypress # Needed for hot-reloading of source code
      - ./public:/usr/src/app/public # Needed for hot-reloading of source code
      - ./.env:/usr/src/app/.env # Needed for hot-reloading the .env
      - ./package.json:/usr/src/app/package.json # Needed for saving changes to package.json
      - ./package-lock.json:/usr/src/app/package-lock.json # Needed for saving changes to package.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - traefik.enable=true
    - traefik.docker.network=tripbot-net
    - traefik.http.services.tripbot_website-svc.loadbalancer.server.port=5173
    - traefik.http.routers.tripbot_website-rtr.rule=Host(`tripbot.${DNS_DOMAIN}`)
    - traefik.http.routers.tripbot_website-rtr.service=tripbot_website-svc
    - traefik.http.routers.tripbot_website-rtr.entrypoints=web
    # - traefik.http.routers.tripbot_website-rtr.tls=true
    # - traefik.http.routers.tripbot_website-rtr.middlewares=chain-no-auth@file
    command: npx vite --host # For development

networks: 
  tripbot-net:
    name: tripbot-net
