version: '3.9'
services:
  tripbot_website:
    container_name: tripbot_website
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    ports:
      - "5173:5173"
    networks:
      - tripbot-net
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - TZ=America/Chicago
    # Run a command against the development stage of the image
    command: npx vite --host

networks: 
  tripbot-net:
    name: tripbot-net
