version: '3.9'
services:
  vue:
    container_name: tripsit_tripbot_website
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
        - frontend
    # network_mode: host
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    working_dir: /usr/src/app

networks: 
  frontend:
    driver: bridge
    name: tripbot_frontend
